import { FoodItem } from "./foodItem";

export const FOOD_ITEMS: FoodItem[] = [
  { id: 1, name: 'Brisket' },
  { id: 2, name: 'Salmon' },
  { id: 3, name: 'Chicken Breast' },
  { id: 4, name: 'Tofu' },
  { id: 5, name: 'Quinoa' },
  { id: 6, name: 'Spinach' },
  { id: 7, name: 'Kale' },
  { id: 8, name: 'Blueberries' },
  { id: 9, name: 'Almonds' },
  { id: 10, name: 'Avocado' },
  { id: 11, name: 'Sweet Potato' },
  { id: 12, name: 'Broccoli' },
  { id: 13, name: 'Lentils' },
  { id: 14, name: 'Oats' },
  { id: 15, name: 'Turmeric' },
  { id: 16, name: 'Garlic' },
  { id: 17, name: 'Ginger' },
  { id: 18, name: 'Chia Seeds' },
  { id: 19, name: 'Apples' },
  { id: 20, name: 'Eggs' },
  { id: 21, name: 'Beets' },
  { id: 22, name: 'Carrots' },
  { id: 23, name: 'Lemons' },
  { id: 24, name: 'Bananas' },
  { id: 25, name: 'Walnuts' },
  { id: 26, name: 'Yogurt' },
  { id: 27, name: 'Brown Rice' },
  { id: 28, name: 'Black Beans' },
  { id: 29, name: 'Avocado Oil' },
  { id: 30, name: 'Chicken Thighs' },
  { id: 31, name: 'Pumpkin Seeds' },
  { id: 32, name: 'Flaxseeds' },
  { id: 33, name: 'Tomatoes' },
  { id: 34, name: 'Cucumbers' },
  { id: 35, name: 'Zucchini' },
  { id: 36, name: 'Watermelon' },
  { id: 37, name: 'Peaches' },
  { id: 38, name: 'Strawberries' },
  { id: 39, name: 'Oranges' },
  { id: 40, name: 'Cottage Cheese' }
];
